const Menu = [{
    id: 1,
    Image:"Images/Meggi.jpg",
    name: "maggie",
    category: "BreakFast",
    Price:30,
    Description: "I like Maggi. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 2,
    Image:"Images/Burger and Potato Fries.jpg",
    name: "Burger & Potato Fries",
    category: "Snacks",
    Price:50,
    Description: "I like Burger & Potato Fries. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 3,
    Image:"Images/chicken-nuggets-lettuce-with-sauce.jpg",
    name: "chicken-nuggets-lettuce-with-sauce",
    category: "Snacks",
    Price:80,
    Description: "I like chicken-nuggets-lettuce-with-sauce. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 4,
    Image:"Images/chinese.jpg",
    name: "chinese",
    category: "Snacks",
    Price:30,
    Description: "I like chinese. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 5,
    Image:"Images/Cooked Pizza Hot.jpg",
    name: "Cooked Pizza Hot",
    category: "Dinner",
    Price:130,
    Description: "I like Cooked Pizza Hot. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 6,
    Image:"Images/cookies With Chai.jpg",
    name: "cookies With Chai",
    category: "BreakFast",
    Price:30,
    Description: "I like cookies With Chai. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 7,
    Image:"Images/crispy-fried-chicken.jpg",
    name: "crispy-fried-chicken",
    category: "Dinner",
    Price:130,
    Description: "I like crispy-fried-chicken. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 8,
    Image:"Images/Rice & Curry.jpg",
    name: "Rice & Curry",
    category: "Dinner",
    Price:70,
    Description: "I like Rice & Curry. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 9,
    Image:"Images/cupcakes.jpg",
    name: "cupcakes",
    category: "BreakFast",
    Price:40,
    Description: "I like cupcakes. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 10,
    Image:"Images/delicious-indian-dosa.jpg",
    name: "delicious-indian-dosa",
    category: "Dinner",
    Price:80,
    Description: "I like delicious indian dosa. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 11,
    Image:"Images/Jira Rice With Panner.jpg",
    name: "Jira Rice With Panner",
    category: "Dinner",
    Price:130,
    Description: "I like Jira Rice With Panner. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 12,
    Image:"Images/Mutton Biriyani.jpg",
    name: "Mutton Biriyani",
    category: "Lunch",
    Price:180,
    Description: "I like Mutton Biriyani. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 13,
    Image:"Images/pasta-tomato-sauce.jpg",
    name: "pasta-tomato-sauce",
    category: "Dinner",
    Price:130,
    Description: "I like pasta-tomato-sauce. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 14,
    Image:"Images/Simple Thali.jpg",
    name: "Simple Thali",
    category: "Lunch",
    Price:130,
    Description: "I like Simple Thali. It's So yummmm. This free lorem ipsum generator lets",
},

{
    id: 15,
    Image:"Images/Vegetable Salad With Wheat Bread.jpg",
    name: "Vegetable Salad With Wheat Bread",
    category: "Lunch",
    Price:130,
    Description: "I like pasta-tomato-sauce. It's So yummmm. This free lorem ipsum generator lets",
},

{
    id: 16,
    Image:"Images/vegetable-chicken-salad.jpg",
    name: "vegetable-chicken-salad",
    category: "Dinner",
    Price:130,
    Description: "I like vegetable chicken salad. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 17,
    Image:"Images/GulabJamun.jpg",
    name: "GulabJamun",
    category: "Dinner",
    Price:30,
    Description: "I like vegetable GulabJamun. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 18,
    Image:"Images/India Large Thali.jpg",
    name: "India Large Thali",
    category: "Dinner",
    Price:330,
    Description: "I like India Large Thali. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 19,
    Image:"Images/Jira Rice With Panner.jpg",
    name: "Jira Rice With Panner",
    category: "Lunch",
    Price:100,
    Description: "I like Jira Rice With Panner. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 20,
    Image:"Images/MutterPanner With Paratha.jpg",
    name: "MutterPanner With Paratha",
    category: "Lunch",
    Price:130,
    Description: "I like MutterPanner With Paratha. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 21,
    Image:"Images/Naan Thali.jpg",
    name: "Naan Thali",
    category: "Dinner",
    Price:160,
    Description: "I like Naan Thali. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 22,
    Image:"Images/Naan With Prawn.jpg",
    name: "Naan With Prawn",
    category: "Dinner",
    Price:130,
    Description: "I like Naan With Prawn. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 23,
    Image:"Images/Panner Somasha.jpg",
    name: "Panner Somasha",
    category: "Snacks",
    Price:30,
    Description: "I like Panner Somasha. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 24,
    Image:"Images/Prawn Chinese.jpg",
    name: "Prawn Chinese",
    category: "Dinner",
    Price:90,
    Description: "I like Prawn Chinese. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 25,
    Image:"Images/Prawn Thali.jpg",
    name: "Prawn Thali",
    category: "Lunch",
    Price:190,
    Description: "I like Prawn Thali. It's So yummmm. This free lorem ipsum generator lets",
},
{
    id: 26,
    Image:"Images/Red Sauce Pasta.jpg",
    name: "Red Sauce Pasta",
    category: "Dinner",
    Price:130,
    Description: "I like Pasta . It's So yummmm. This free lorem ipsum generator lets",
},

];
export default Menu;